type BuildPromptParams = {
    project: any;
    updates: any[];
    recentContent: any[];
    preferenceMemory?: any[];
    platform: string;
    perspective: string;
    tone: string;
    contentLength: string;
};

export function buildPrompt({
    project,
    updates,
    recentContent,
    preferenceMemory,
    platform,
    perspective,
    tone,
    contentLength,
}: BuildPromptParams) {
    const updatesText = updates
        .map(
            (update, index) =>
                `${index + 1}. ${update.content}`
        )
        .join("\n");

    const recentContentText =
        recentContent.length > 0
            ? recentContent
                .map(
                    (content, index) =>
                        `${index + 1}. ${content.content}`
                )
                .join("\n\n")
            : "No previous generated content.";

    const preferenceMemoryText =
        preferenceMemory && preferenceMemory.length > 0
            ? preferenceMemory
                .map(
                    (content, index) =>
                        `Example ${index + 1}:\n- Blueprint: ${JSON.stringify(content.contentProfile)}\n- Final Output: "${content.content}"`
                )
                .join("\n\n")
            : "No previous preference memory.";

    return `
You are helping a builder create content about their work.

PROJECT CONTEXT

Project Name:
${project.name}

Project Description:
${project.description}

Target Audience:
${project.audience.join(", ")}

Industry:
${project.industry.join(", ")}

Tags:
${project.tags.join(", ")}

CONTENT SETTINGS

Platform:
${platform}

Perspective:
${perspective}

Tone:
${tone}

Content Length:
${contentLength}

PLATFORM INSTRUCTIONS

${getPlatformInstructions(platform)}

${getPerspectiveInstructions(perspective)}

${getToneInstructions(tone)}

${getLengthInstructions(contentLength)}

CURRENT WORK UPDATES

${updatesText}

PREVIOUS GENERATED CONTENT

${recentContentText}

USER STYLE PREFERENCES

The user has previously selected the following generated content for similar updates. 
Use these as REFERENCE EXAMPLES for how the user prefers their content to be structured, hooked, and written.
Do not blindly copy them as templates. Learn the user's style and preferences while generating fresh content.

${preferenceMemoryText}

IMPORTANT INSTRUCTIONS

1. Create content primarily from the CURRENT WORK UPDATES.

2. Use the PROJECT CONTEXT only when it helps explain the updates.
Do not summarize the project unless the updates require that context.

3. Use the selected PERSPECTIVE consistently throughout the content.

4. Use the selected TONE consistently throughout the content.

5. Follow the style expected for the selected PLATFORM.

6. Avoid repeating hooks, phrases, wording, themes, openings, or conclusions from PREVIOUS GENERATED CONTENT.

7. Do not invent features, achievements, metrics, users, revenue, customers, outcomes, challenges, lessons, decisions, problem setups, pain points, or results that are not explicitly mentioned.

8. If an update is simple, keep the content simple.

9. Do not expand small updates into long stories.

10. Do not assume motivations, unstated personal intentions, or technical decisions unless they are explicitly mentioned.

11. Write like a real practitioner or creator sharing progress with a peer, not like a company writing a press release. Anchor the content naturally using the selected PERSPECTIVE near the beginning, but do not repeat the pronoun at the start of every sentence. Maintain natural human writing flow.

12. Write as recent hands-on work completed. Use natural human discovery verbs rather than corporate changelog or press release verbs. Rewrite any buzzwords or hype into plain, everyday language.

13. Do not invent corporate hype, buzzwords, or fake marketing excitement. Avoid corporate value judgments and vague jargon. Allow subtle, authentic human expressions if natural to the context.

14. Avoid headlines, post titles, meta-activity intros, and status-report filler that describe the act of working rather than the work itself. Open naturally with the actual context or action.

15. Use simple English.

16. Use short and natural sentences.

17. Sound human.

18. Avoid sounding like:
- a marketer
- a startup founder pitching investors
- a corporate PR department
- a blog writer
- an AI assistant

19. Avoid buzzwords completely.

20. Focus on what was actually completed.

21. Be specific.

22. The content should feel like it was written naturally by a human creator, not generated by AI.

23. Do not write like a LinkedIn influencer.

24. Do not use motivational language.

25. Do not add life lessons.

26. Do not add productivity advice.

27. Do not add generic takeaways.

28. Stay close to the updates provided.

29. Prefer sharing recent work completed over explaining how the product works.

30. Prefer concrete actions over descriptions.

31. If the update is small, the content should also be small.

32. Do not turn routine work into a milestone.

33. Focus on facts first, explanations second.

34. Do not repeat the updates verbatim.
Rewrite them naturally while staying faithful to the information provided.
Do not turn the content into a changelog or task list.

35. Format the content for readability.

36. Use short paragraphs separated by blank lines.

37. Most paragraphs should be 1-3 sentences long.

38. Break up dense blocks of text when appropriate.

39. Prioritize readability for social media platforms.

You MUST return the output as a valid JSON object containing exactly 2 natural variations of the content.
Both variations must use the same platform, tone, perspective, and length.
Both Variation 1 and Variation 2 must be grounded in the updates. Variation 1 should focus on the action completed. Variation 2 should focus on the situation or risk encountered followed by the solution, while both remaining equally natural, grounded, and clean.
Additionally, you MUST generate a contentProfile for each variation explaining its blueprint. The contentProfile should contain topics, technologies, hookStyle, structure, contentAngle, writingTone, and detailLevel.

IMPORTANT FORMATTING RULE: You MUST use "\\n\\n" (literal newline characters) inside your "content" string to break the text up into short, readable paragraphs! Do not write one massive block of text.
`;
}

function getPlatformInstructions(
    platform: string
) {
    switch (platform) {
        case "LINKEDIN":
            return `
LINKEDIN RULES

- Write like a professional sharing work completed.
- Do not write like a corporate announcement.
- Focus on the work completed.
- Mention lessons or insights only if they are present in the updates.
- Use clear paragraphs.
- Sound authentic and transparent.
- Avoid excessive emojis.
- Avoid clickbait.
`;

        case "TWITTER":
            return `
TWITTER RULES

- Write conversationally for X/Twitter like a real practitioner sharing progress with followers.
- Open naturally with the work or context without artificial hype hooks.
- Use natural spacing with short paragraphs (1-2 sentences) separated by blank lines.
- Avoid robotic single-line summaries or punchy bullet points.
- Sound authentic and transparent.
- Make the post easy to scan on mobile devices.

If Content Length is SHORT:
- Keep the post under 280 characters.
- Create a single tweet.

If Content Length is MEDIUM:
- Create a detailed single tweet.
- Stay reasonably concise.

If Content Length is LONG:
- Always generate a single post.
- Never generate a thread.
- Never use tweet numbering.
- Never use 1/, 2/, 3/.
- Never use Thread: or 🧵.
- LONG means a longer single post, not a thread.
`;

        case "REDDIT":
            return `
REDDIT RULES

- Write like a builder sharing progress with a community.
- Tell a brief story: explain the context, the problem, what you tried, and the result.
- Keep it conversational, honest, and problem-focused.
- Do NOT use marketing language, startup buzzwords, or hype.
- Do not add artificial engagement bait.
- Prefer sharing a challenge you faced and how you solved it.
- Format with clear, short paragraphs.
`;

    }
}

function getPerspectiveInstructions(
    perspective: string
) {
    switch (perspective) {
        case "FIRST_PERSON":
            return `
PERSPECTIVE RULES

- Write from a first-person perspective.
- Use words like:
  - I
  - Me
  - My
`;

        case "TEAM":
            return `
PERSPECTIVE RULES

- Write from a team perspective.
- Use words like:
  - We
  - Us
  - Our
`;

        default:
            return "";
    }
}

function getToneInstructions(
    tone: string
) {
    switch (tone) {
        case "PROFESSIONAL":
            return `
TONE RULES

- Use a professional tone.
- Be clear and direct.
`;

        case "CASUAL":
            return `
TONE RULES

- Use a casual and approachable tone.
- Keep the writing conversational.
`;

        case "TECHNICAL":
            return `
TONE RULES

- Use a technical tone.
- Discuss implementation details when present.
- Discuss engineering decisions only if mentioned in the updates.
- Do not invent technical challenges.
`;

        case "STORYTELLING":
            return `
TONE RULES

- Use a storytelling style.
- Create a narrative around the work completed.
- Build a narrative around the completed work.
- Only mention challenges, decisions, or outcomes if they are explicitly present in the updates.
`;

        default:
            return "";
    }
}

function getLengthInstructions(
    contentLength: string
) {
    switch (contentLength) {
        case "SHORT":
            return `
LENGTH RULES

- Generate concise content.
- Remove unnecessary details.
`;

        case "MEDIUM":
            return `
LENGTH RULES

- Generate balanced content.
- Include enough detail to explain progress.
`;

        case "LONG":
            return `
LENGTH RULES

- Generate detailed content.
- Add more detail from the updates.
- Explain completed work more thoroughly.
- Do not invent challenges, decisions, lessons, or outcomes.
`;

        default:
            return "";
    }
}